version: '3.1'
services:
  mysql-container:
    image: mysql:latest
    environment:
        - MYSQL_ROOT_PASSWORD=admin
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=admin
        - MYSQL_DATABASE=product
        - MYSQL_PORT=3306
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./bootstrap.sql:/docker-entrypoint-initdb.d/bootstrap.sql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
